### ISSUE TITLE
Which version and flavor of JATS?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#105]
This was discussed a little bit in the telecon this morning, mostly regarding the difference between green (archiving) and blue (publishing).

Some questions for us to consider:
* Do we want to wade into the green-vs-blue debate, and recommend one over the other? 
* How do our recommendations change depending on the version/flavor of JATS in use? We already have one concrete example of this, in the NISO ALI recommendation - those elements don't exist in any version of JATS earlier than 1.1d3. It means that some recommendations have to have a "scope" attribute attached, I think.

Some people this morning said that blue is often too restrictive. I think the trouble with green is that it is way too permissive, and one of the focusses of this group is regularizing a lot of the markup. Brainstorming, I am wondering if we might be able to validate green documents against the blue JATS schema, and make validation errors into JATS4R warnings, for example.

Here are some notes from the minutes of the telecon this morning:

* Most people are using blue
* Green is more suitable for the purposes of this group
* More suitable for reuse and archival therefore this group
* Every valid blue file is automatically valid in green
* We should not be recommending a version
* So either make recommendations to JATS standing committee to make changes to blue or make sure recommendations work in blue

**Comment by hubgit** [comment]
Given that the recommendations are for _publishing_ XML, it would make sense to base those recommendations on the Publishing DTD.

Is anyone publishing article XML using the Archiving DTD?

**Comment by vincentml** [comment]
>> Is anyone publishing article XML using the Archiving DTD?

Yes, most definitely. 

The Publishing DTD makes a certain set of choices about what to restrict based on the Archiving DTD. Those choices don't meet with every publishers' needs. In our version of JATS we started with the Archiving DTD and chose restrictions that are in some areas similar to the Publishing DTD and in some areas different than Publishing DTD.

**Comment by hubgit** [comment]
>> Is anyone publishing article XML using the Archiving DTD?

> Yes, most definitely.

Can you point to an example XML file online?

**Comment by jeffbeckncbi** [comment]
All of the PMC articles - including the ones from the OAI that Daniel used to first complain about them (and get this whole thing started) are tagged in version of the Archiving Tag Set.

**Comment by hubgit** [comment]
> All of the PMC articles […] are tagged in version of the Archiving Tag Set.

Were they originally published in that format, or converted to the Archiving DTD for archiving?

**Comment by jeffbeckncbi** [comment]
Most, but not all, were created in Publishing. We have a good number of publishers sending us content in Archiving models.

**Comment by hubgit** [comment]
> We have a good number of publishers sending us content in Archiving models.

It might be useful to know who those are and which elements they're using that aren't in the Publishing DTD. Maybe that's out of scope for this group, though.

**Comment by Klortho** [comment]
We discussed this at the last telecon. (Two weeks ago already, so I don't remember it that clearly)

I think the consensus was that there are some good reasons to use Green, and so we really can't recommend that publishers use Blue. Among the reasons is that some attributes in Blue are defined as a fixed set of values (token type) whereas in Green they are open to any value.

One of the ideas that came up was that we could look at the differences between the two, and incorporate some of the Blue rules into our schematrons. There's even a tool, dtdschematron, that would convert the Blue DTD into schematron for us.

**Comment by Nikos-Markantonatos** [comment]
All our client publishers are using the Green DTD because that's the DTD that the Atypon platform supports. To be honest, I never understood why one should limit themselves to the Blue DTD when the Green DTD offers higher flexibility and more functionality. The argument that the Green DTD is "too permissive" is rather mute, because DTDs are by definition too permissive, that's why people resort to Schematron and other such techniques to harness XMLs in how they want them to be encoded. On the other hand, Blue DTD is becoming Greener by the day to the degree that the JATS committee is considering dropping the distinction between the two flavors in the future. In fact, this will actually be good news to the JATS4R initiative, because that's one less DTD flavor to write recommendations about.

But in any case, I see no concrete arguments whereby JATS4R would recommend Blue in favor of Green. In fact, the fixed set of values in Blue are an indication that Green maybe the preferred DTD flavor.

**Comment by Klortho** [comment]
I wrote this up, that we are flavor-agnostic.
