### ISSUE TITLE
Questions about the Schematron(s)

### ISSUE THREAD

**Issue by jeffbeckncbi** [JATS4R/elements#18]
I've started working on building the tests for the Permissions topic and the Formula topic. There are a few decisions about how we want the Schematron to be that we need to make before we get too far into this. 

1. Should we use &lt;phase>? &lt;phase> allows users applying the Schematron to select a subset of the tests that they will apply. (see https://github.com/JATS4R/elements/issues/10). The issue is that xmllint (the libxml parser) does not run Schematrons with &lt;phase>. I think most other processors will run it. 
In issue #10 I suggested to use \<phase> to allow users to select which of the topic-specific rules they want to apply, but there may be other uses (see 2 below).

2. Should we make tests for Errors only? Do we want to write Warnings and possibly Information or reminders? A good example of this would be when we find an \<ext-link> in \<license-p>. Our guidance says that this link must be to a human readable license that will not be read by machines. This is not something that we can tell when running the Schematron, but we could report this when we find license-p/ext-link:
> "REMINDER: Any link in the text of the license should be to a human-readable license page that does not contradict the machine-readable license referenced by license/@xlink:href."

   We could accomplish this with &lt;phase>, if we decide to use them. But we will need to decide to use \<phase> for topic selection or level of reporting. Using &lt;phase> for both would be unwieldy for users and maintenance of the Schematron. 

3. Does the Schematron need to work with BITS?

4. Because CC licenses are the only ones that currently meet our requirement for having a canonical, persistent, published URI that identifies it, do we want to test for a Creative Commons URI when we find license/@xlink:href?

**Comment by rupertgatti** [comment]
I have no experience building a Schematron, but would suggest just sticking to the basics initially - no warnings, and no need for BITS  - but allow for the inclusion of both at a later stage.

Personally I dislike too many warnings as it can become a little bit 'nanny state' - but placing warnings where consistent bad practice is observed in papers otherwise 'passing' the Schematron would be helpful. If we find that, despite our recommendations, a lot of people using the Schematron ARE still linking to non-human readable or inconsistent licence urls, for example, then maybe that would be a good time to add a warning. 

And I suspect (with absolutely no data at hand to support it) thats BITS usage is a couple of orders of magnitude less than JATS usage. So I would suggest keeping things as simple as possible to start with and not worrying about BITS until there is sufficient call by users to do so. Certainly OBP is still someway from having content sufficiently well formatted in BITS to test the Schematron with.

Rupert

**Comment by Melissa37** [comment]
Ahh, I am opposite - I like the idea of warnings and info reminders :-)

**Comment by Klortho** [comment]
We'll keep what we have now, and add a drop-down select, as Alf suggests [here](https://github.com/JATS4R/validation/issues/8). Default will be "errors".

**Comment by Melissa37** [comment]
Decision:
Drop down select box, 3 options:
Errors only
Warnings and errors
Warnings, Information and errors

**Comment by Klortho** [comment]
I'm going to close this, as Melissa suggested in her email.  One item, number 4 above, is covered by #28 , I think.
