### ISSUE TITLE
How to define custom tex macros?

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/elements#40]
This is a request to JATS?

Add element to capture TeX definitions used by author, e.g.

```
<tex-defs>
\def\rmi{{\rm i}}
...
\def\rme{{\rm e}}
</tex-defs>
```

The element would go at the start of "article-meta", so that even the title can include author macros.

**Comment by Klortho** [comment]
Yes, I think this would be a suggestion to the JATS committee. As for our group, I think we need to stay within the bounds of what's allowed by JATS right now. I don't see any other easy way to include these defs inside article-meta within the existing JATS, but somebody else might have a good idea.

**Comment by Klortho** [comment]
In the last telecon, Jeff suggested we could use [\<custom-meta>](http://jatspan.org/niso/publishing-1.1d1/#p=elem-custom-meta).

Can we agree to add this to the examples and recommendations?  I'd suggest using @specific-use = "tex-math", with this as an example:

```xml
...
<article-meta>
  ...
  <custom-meta specific-use="tex-math">
    \def\rmi{{\rm i}}
    \def\rme{{\rm e}}
  </custom-meta>
</article-meta>
...
```

**Comment by kaveh1000** [comment]
My concern is that I believe custom-meta is not at the beginning of the document. When rendering the XML in a browser, say, will it be possible to use these definitions in the Title or Abstract? Can we reorder the XML when converting to HTML?

**Comment by Klortho** [comment]
custom-meta is allowed in custom-meta-group, which is allowed in [article-meta](http://jatspan.org/niso/publishing-1.1d1/#p=elem-article-meta) and [front-stub](http://jatspan.org/niso/publishing-1.1d1/#p=elem-front-stub). So, yes, it would be at the beginning of the document.

**Comment by doylemd** [comment]
I would think that to maximize reuse, best practice would not be to include TeX macro definitions at all in the file. Rather the use of TeX macros should be expanded out each place it is used within the document. This would make is easier, for instance, to pull out a fragment of the document without worrying about having to parse the rest of it looking for macro definitions.

That said, if custom-meta is used, the specific-use attribute should be more expressive than just "tex-math" because it doesn't make it clear that TeX macros are being defined. So I would suggest using specific-use="tex-math-definitions" or perhaps "tex-macros".

**Comment by jeffbeckncbi** [comment]
On the 2015-03-05 call, the group decided to allow custom definitions to be defined at the article level. When I was working on the Recommendations document, I realized that the example was not valid JATS. I've modified it to 

```
<article-meta>
  ...
  <custom-meta>
     <meta-name>tex-math-definitions</meta-name>
     <meta-value>
          \def\rmi{{\rm i}}
          \def\rme{{\rm e}}
     </meta-value>
  </custom-meta>
</article-meta>

```
We don't need to specific-use attribute because &lt;meta-name&gt; is required and will meet the same need.

**Comment by Klortho** [comment]
Updated the recommendations [here](https://github.com/JATS4R/elements/wiki/Math#tex-math-macro-definitions)
