### ISSUE TITLE
Cascading permissions?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#8]
Questions / concerns about Open Book Publishers permissions example

1. In many places, there are two \<license> elements side-by-side, which is ambiguous (not machine-readable).  It would not clear to a machine whether it indicates a dual license, or two ways of calling out the same license.  After looking it over, it's clear what it means:  that the content is generally under the CC license, but that the document at the second URL has qualifications and caveats.

2. In that \<license> elements' xlink:href attribute, the URL "http://www.openbookpublishers.com/isbn/9781783740178#copyrighttab" appears.  This is not the canonical URI *identifier* of any license, but rather a URL link to a page that has the license documentation.  The link is broken, too: it seems that it has changed to this: http://www.openbookpublishers.com/product/233#copyright.  This is a good illustration of why only canonical, published, persistent URIs should be used in that attribute.

3. So, for the first \<permissions> element in that example, I would retag it something like this:

      ```xml
      <license license-type="open-access"
               xlink:href="http://creativecommons.org/licenses/by-nc-nd/4.0/"/>
        <license-p>This entire volume is published under a Creative Commons
          Attribution-NonCommercial-NoDerivatives 4.0 ...
          See permissions relating to individual images. Detailed information 
          is available at 
          <ext-link ext-link-type="uri" 
            xlink:href="http://www.openbookpublishers.com/product/233#copyright"
              >http://www.openbookpublishers.com/product/233#copyright</ext-link>.</license-p>
      </license>
      ```

4. Inside \<fig id="fig1">, there is this: "\<copyright-statement>The National Portrait Gallery, London. All rights reserved\</copyright-statement>".  Here, the \<license> element, that has the same URL as the others. In order to have this machine-readable, do we need a canonical persistent URI that means "all rights reserved"?

**Comment by hubgit** [comment]
The [JATS schema](http://jatspan.org/niso/publishing-1.0/#p=elem-permissions) lists the elements in which the `permissions` element can be found.

Given that the purpose of allowing the `permissions` element in these places is presumably to allow permissions to be specified for a sub-element separately from the main article, it would be useful to have a table that specifies which element of the article is covered by a `permissions` element in a certain location:

| `permissions` container | Element to which permissions apply | Notes |
|-----------------------|------------------------------------|-------|
| `array` | `array` | Self |
| `article-meta` | `article` | Closest parent `article` element |
| `boxed-text` | `boxed-text` | Self |
| `chem-struct-wrap` | `chem-struct-wrap` | Self |
| `disp-quote` | `disp-quote` | Self |
| `fig` | ? | The whole figure, and any associated files? |
| `front-stub` | `response` or `sub-article` | The closest `response` or `sub-article` parent |
| `graphic` | `graphic` | The image file (`@xlink:href`) - and its description? |
| `media` | `media` | The media file (`@xlink:href`) - and its description? |
| `preformat` | `preformat` | Probably intended for code blocks? |
| `sec-meta` | `sec` | Closest parent `sec` element |
| `statement` | `statement` | Self |
| `supplementary-material` | `supplementary-material` | The supplemental file (@xlink:href) - and its description? What about `inline-supplementary-material`? |
| `table-wrap` | `table-wrap` | The table, caption etc |
| `table-wrap-foot` | `table-wrap` | Closest parent `table-wrap` element |
| `verse-group` | `verse-group` | Self |

**Comment by hubgit** [comment]
It seems that nested permissions can't work if the nested permission is more restrictive (if you have permission to redistribute the whole article, you can't not have permission to redistribute a part of it), but some sections/files could be given less restrictive permissions?

**Comment by Melissa37** [comment]
I have a really tricky one, which I have only just been made aware of. We have parts of composite figures that are under separate copyright. In one figure I have 4 separate copyrights to account for, 2 all rights reserved, one CC-BY and one reprinted with permission only. I am guessing my only option is to make the whole figure all rights reserved and in the license-p add the separate details? The editorial department is reluctant to do this as some is CC-BY, but I can see no alternative. Any thoughts? 
I appreciate this whole thread is not complete and resolved, but I'd like to ensure I am at least partway right for now rather than completely wrong!

**Comment by Melissa37** [comment]
Sorry, just tried this a bit more and I can validate the xml file with multiple permission statements...

**Comment by vincentml** [comment]
Melissa: Could you tag the composite figure using fig-group with nested fig elements, and tag each fig with it's own permissions element?

**Comment by Melissa37** [comment]
But think that would be confusing as it is loaded as one figure file?

**Comment by Melissa37** [comment]
#23 closed as too similar to this issue, but referenced here

**Comment by Daniel-Mietchen** [comment]
@Melissa37 Having a figure or subfigure non-compliant with CC BY is technically possible, but a CC BY journal doing so would cease to be one.

On a sidenote, composite figures in non-editable formats are a reuse barrier in and of themselves, even if openly licensed, because adapting them to different reuse scenarios (e.g. translation into another language) can be difficult and sometimes impossible, and there is always a quality loss when downscaling original images or adding label text or arrows in bitmap layers.

**Comment by Melissa37** [comment]
"Subject to a Creative Commons Attribution license, except where otherwise noted."
We've had 5 instances of non-compliant figures.
One option would be to not allow them at all - but that will detract from the scientific message and hinder the reader. They are pretty rare and it is always clear to the human reader that they are non-CC-BY - I am just sorting out the xml so it's tagged up. We do need to resume this topic discussion and get more input from the publishers who have joined the group since Christmas. 

Am in agreement about composite figures, but there is a lot of work for authors to do this, and also for publishers and their online hosting platforms to accommodate it, so I don't think it will be a quick thing to change.

**Comment by hubgit** [comment]
If a publisher adds a separate `<permissions>` element to a figure that has restricted copyright than the rest of the article (but which is allowed to be used in articles that are CC-BY licensed), will any tools recognise that permissions notice? 

If so, would should they do with the information?

**Comment by Melissa37** [comment]
Can anyone thing of examples of where this content might not be figures?
Figures are discrete elements of an article/chapter that could be treated as separate from the rest of the article, theoretically.

**Comment by Melissa37** [comment]
See: http://publishingresearchconsortium.com/index.php/prc-guides-main-menu/166-open-access-licensing-0215

See page 28 of this document: Permissions typically not included or reserved in Open Access
Licences
Permissions typically not included or reserved in Open Access
Licences
a) Third-party content
Nobody can validly license content to which they have no rights. Thus, Open Access Licences
inherently do not cover any third-party content embedded in OPC, third-party illustrations,
photographs, chunks of text that the author-researcher proposes to use as part of his
unpublished manuscript, or supplementary content such as data sets, videos, sounds, etc.
Third party content may be so embodied in OPC because sometimes the authors may in fact not
need a licence to do so under local copyright laws, as the inclusion would be covered under an
exception, such as making a quotation. However, more often uses are proposed or licensable to
the public that would go beyond those permitted in national exceptions. The authors should
thus seek permission in order to include this third party material. Where the third-party content
is itself subject to an Open Access Licence, the authors would incorporate the content based on
that licence and consistent with its requirements, e.g. attribution, link back to the rightsholder’s
version, uses free from DRM, and any other requirements, e.g. statement of non-modification or
modification of the content depending on permissions available. Where the third-party content
is proprietary, then it would be misleading to embed the content into OPC without clearly
marking it as another licence. This author would recommend a prominent demarcation of such
content so that users are aware that they might need additional copyright licences if they wish to
make a copyright use of the content in question.

Unfortunately the xml tagging is still not covered.

**Comment by Klortho** [comment]
Owen wrote,

> My [only] concern about the cascading aspects is that the cascade is logically not through 
> the XML hierarchy - would we need rules that defined how the cascade worked that were 
> machine processable?"

I think Alf's table addresses this concern.  I have added it to [the
recommendations](https://github.com/JATS4R/elements/wiki/Permissions).

Daniel wrote,

> Suppose I am building an online library that brings CC-licensed books together .... 
> your current example would require me to go through the entire book and look for something 
> that lacks an explicit license statement. I thus think the book as a whole should be tagged 
> as "All rights reserved", and everything available under other conditions should be tagged 
> accordingly.

I think that Bianca's example, and also the document, [Open Access 
Licensing](http://publishingresearchconsortium.com/index.php/prc-guides-main-menu/166-open-access-licensing-0215), 
that [Melissa linked to](https://github.com/JATS4R/elements/issues/8#issuecomment-76940020) 
suggest that the idea that OA material can have some more restrictively licensed content
is a valid one.

Note that with the tagging recommendations we have right now, it's possible to do either:

* Put the OA license on the container, and override that for all restrictively-licensed content, or
* Put an "all right reserved" permissions element on the container, and override that for all OA-licensed
  content.

The question is, do we want to add anything to the recommendations regarding this discussion?
I think maybe a summary gleaned from a couple of the above comments would be good.

Bianca wrote,

> Would a solution be to include a 'multi-licence' tag somehow - that would flag 
> early on that some content is included under a different licence to the 'parent'?

I don't think so. It should be enough to put that into the human-readable \<license-p>, and 
have the machine-readable scheme that we're proposing here. It's (relatively) easy for a 
machine to find all the \<license> elements in a document, and see if they agree.

Melissa wrote,

> We have parts of composite figures that are under separate copyright....

I don't see any way to handle this for machine-readability, within JATS, if the composite 
parts are not exposed. The whole figure would have to be tagged as "all rights 
reserved", and not available to any bots. But, of course, the \<license-p> element
could explain the situation to humans.

> ....Unfortunately the xml tagging is still not covered.

I think we've got it covered in our example.

**Comment by hubgit** [comment]
The simplest recommendation for a machine that's processing the XML could be to take the `permissions` element in the `article-meta` element as applying to the whole article, but if there's a `permissions` element anywhere else in the article then it should flag the whole article for manual processing, as the current rules are too vague to be able to know what might be covered by the separate permissions statement.

**Comment by biancagualandi** [comment]
Melissa asked:

> Can anyone think of examples of where this content might not be figures?

At least one of OBP titles has third-parties recordings embedded in the text which are not under the same license as the rest. More specifically, the text is under a CC BY-NC-ND license, while some of the recordings are in the public domain, and some are all rights reserved. 

In all the cases I can think of, the different license applies to elements that are separate from the rest of the article/book.

**Comment by Klortho** [comment]
When/if we get this resolved, we could add this back into the JATS-Con paper:

> We have further established rigorous guidelines for the scope of the <permissions> element, depending on where in the document it appears.

**Comment by Melissa37** [comment]
In response to Alf's comment: 

> but if there's a permissions element anywhere else in the article then it should flag the whole article for manual processing

As the permission is contained within a container (the containers it could be listed in are in the table above), could the bot just regard that complete container?

**Comment by hubgit** [comment]
> As the permission is contained within a container (the containers it could be listed in are in the table above), could the bot just regard that complete container?

It could, but my table was just a rough guess at what the containers should be, and in many cases it wasn't clear. The safest recommendation would be just "if there are multiple permissions elements, the processor is going to have to do extra work, possibly manual, to work out what they apply to".

**Comment by Melissa37** [comment]
All agreed. Need to write up the notes more - which elements it can be used in. Can close this issue once done.
Jeff to provide info in the Schematron - not right/wrong rules.
See meeting minutes 2nd April.

**Comment by Melissa37** [comment]
Agreed on call - 16th April. Close case.

**Comment by Klortho** [comment]
FYI, in response to a comment @hubgit wrote in the table, I added [this comment](http://www.niso.org/apps/group_public/view_comment.php?comment_id=581) on the NISO site about adding permissions to \<inline-supplementary-material>
